version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-7.0-centos
    ports:
      - "6868:443"
      - "2662:22"
    volumes:
      - ./html:/var/www/html
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/httpd/sites-available
      - ./config/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - ./config/welcome:/etc/motd
      - ./config/sudoers:/etc/sudoers
      - ./config/crontabs:/var/spool/cron/crontabs
      - ./config/ssh/sshd_config:/etc/ssh/sshd_config
      - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    restart: always
    hostname: orangehrm-jade-web
    container_name: jade_web