version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-7.1-centos
    ports:
      - "7878:443"
      - "2882:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    - ./config/pam/su:/etc/pam.d/su
    - ./config/pam/sshd:/etc/pam.d/sshd
    - ./config/pam/password-auth:/etc/pam.d/password-auth
    - ./config/pam/login:/etc/pam.d/login
    - ./config/pam/system-auth:/etc/pam.d/system-auth
    - ./config/security/access.conf:/etc/security/access.conf
    - ./config/resolve-permission.sh:/etc/resolve-permission.sh
    - ./config/resolve.conf:/etc/resolve.conf
    - ./config/php7/php.ini:/etc/php.ini
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-enabled
    - ./config/apache2/cert:/etc/httpd/cert
    - ./config/apache2/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./logs/ubuntu_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/hostname:/etc/hostname
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/ldap/cert:/etc/openldap/cacerts
    - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
    - ./config/ldap/nslcd.conf:/etc/nslcd.conf
    - ./config/ldap/sudo-ldap.conf:/etc/sudo-ldap.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

    privileged: true
    links:
      - db
    restart: always
    networks:
      infinitynet:
        ipv4_address: 172.40.0.71
    hostname: infinity-server
    container_name: infinity_web

  db:
    image: mariadb:10.2
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      infinitynet:
        ipv4_address: 172.40.0.102
    restart: always
    hostname: orangehrm-infinity-db
    container_name: infinity_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "7879:80"
    networks:
      infinitynet:
        ipv4_address: 172.40.0.20
    environment:
      PMA_HOST: db
    restart: always
    container_name: infinity_phpmyadmin

volumes:
  mariadb102:

networks:
  infinitynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.40.0.2/16
         gateway: 172.40.0.1
