version: '2.2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-php-7.4.19-rhel-8
    ports:
      - "6464:443"
      - "2222:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    # - ./config/pam/su:/etc/pam.d/su
    # - ./config/pam/sshd:/etc/pam.d/sshd
    # - ./config/pam/password-auth:/etc/pam.d/password-auth
    # - ./config/pam/login:/etc/pam.d/login
    # - ./config/pam/system-auth:/etc/pam.d/system-auth
    - ./config/security/access.conf:/etc/security/access.conf
    - ./config/resolve-permission.sh:/etc/resolve-permission.sh
    - ./config/resolve.conf:/etc/resolve.conf
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-enabled
    - ./config/apache2/cert:/etc/httpd/cert
    - ./config/apache2/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./logs/ubuntu_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/hostname:/etc/hostname
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/openldap/cacerts:/etc/openldap/cacerts
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - ./config/sssd/sssd.conf:/etc/sssd/sssd.conf
    - ./config/openldap/ldap.conf:/etc/openldap/ldap.conf
    privileged: true
    links:
      - db
    restart: always
    networks:
      atomnet:
        ipv4_address: 172.74.0.74
    hostname: atom-server
    container_name: atom_web

  db:
    image: orangehrm/orangehrm-db-images:mariadb-10.4.22-redhat-8.4
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      atomnet:
        ipv4_address: 172.74.0.102
    restart: always
    hostname: orangehrm-atom-db
    container_name: atom_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "6465:80"
    networks:
      atomnet:
        ipv4_address: 172.74.0.20
    environment:
      PMA_HOST: db
    restart: always
    container_name: atom_phpmyadmin

volumes:
  mariadb102:

networks:
  atomnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.74.0.0/16
         gateway: 172.74.0.1
