version: '2.2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-php-7.4-ubuntu-20.04
    ports:
      - "7474:443"
      - "2992:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    - ./config/pam/su:/etc/pam.d/su
    - ./config/pam/sshd:/etc/pam.d/sshd
    - ./config/pam/password-auth:/etc/pam.d/password-auth
    - ./config/pam/login:/etc/pam.d/login
    - ./config/pam/system-auth:/etc/pam.d/system-auth
    - ./config/security/access.conf:/etc/security/access.conf
    - ./config/resolve-permission.sh:/etc/resolve-permission.sh
    - ./config/resolve.conf:/etc/resolve.conf
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-enabled
    - ./config/apache2/cert:/etc/httpd/cert
    - ./config/apache2/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./logs/ubuntu_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/hostname:/etc/hostname
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/ldap/cert:/etc/openldap/cacerts
    - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
    - ./config/ldap/nslcd.conf:/etc/nslcd.conf
    - ./config/ldap/sudo-ldap.conf:/etc/sudo-ldap.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty : true
    privileged: true
    links:
      - db
    restart: always
    networks:
      bishopnet:
        ipv4_address: 172.24.0.74
    hostname: bishop-server
    container_name: bishop_web

  db:
    image: orangehrm/orangehrm-db-images:mariadb-10.5.13-ubuntu-20.04
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb105_ubuntu:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      bishopnet:
        ipv4_address: 172.24.0.102
    restart: always
    hostname: orangehrm-bishop-db
    container_name: bishop_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "7465:80"
    networks:
      bishopnet:
        ipv4_address: 172.24.0.20
    environment:
      PMA_HOST: db
    restart: always
    container_name: bishop_phpmyadmin

volumes:
  mariadb105_ubuntu:

networks:
  bishopnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
         gateway: 172.24.0.1
