version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-5.6-centos
    ports:
    - "6767:443"
    - "2552:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-available
    - ./config/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/ldap/cert:/etc/openldap/cacerts
    - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
    - ./config/ldap/nslcd.conf:/etc/nslcd.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

    privileged: true
    restart: always
    hostname: Phantom-Server
    container_name: phantom_web
  #  extra_hosts:
  #  - "ldap.orangehrm.com:172.18.0.1"
  #  - "ftp.orangehrm.com:172.18.0.1"