version: '2.2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:uat-7.4-centos-remi
    ports:
      - "6464:443"
      - "2222:22"
    volumes:
    - ./html:/var/www/html
    - ./home:/home
    - ./config/pam/su:/etc/pam.d/su
    - ./config/pam/sshd:/etc/pam.d/sshd
    - ./config/pam/password-auth:/etc/pam.d/password-auth
    - ./config/pam/login:/etc/pam.d/login
    - ./config/pam/system-auth:/etc/pam.d/system-auth
    - ./config/security/access.conf:/etc/security/access.conf
    - ./config/resolve-permission.sh:/etc/resolve-permission.sh
    - ./config/resolve.conf:/etc/resolve.conf
    - ./config/mysql-client:/etc/mysql
    - ./config/apache2/sites-available:/etc/httpd/sites-enabled
    - ./config/apache2/cert:/etc/httpd/cert
    - ./config/apache2/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./logs/ubuntu_logs:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - ./config/hostname:/etc/hostname
    - ./config/welcome:/etc/motd
    - ./config/sudoers:/etc/sudoers
    - ./config/crontabs:/var/spool/cron/crontabs
    - ./config/ssh/sshd_config:/etc/ssh/sshd_config
    - ./config/ldap/cert:/etc/openldap/cacerts
    - ./config/ldap/nsswitch.conf:/etc/nsswitch.conf
    - ./config/ldap/nslcd.conf:/etc/nslcd.conf
    - ./config/ldap/sudo-ldap.conf:/etc/sudo-ldap.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

    privileged: true
    links:
      - db
      - rabbitmq
    restart: always
    networks:
      guardiannet:
        ipv4_address: 172.74.0.74
    hostname: guardian-server
    container_name: guardian_web

  db:
    image: orangehrm/orangehrm-db-images:mariadb-10.2
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      guardiannet:
        ipv4_address: 172.74.0.102
    restart: always
    hostname: orangehrm-guardian-db
    container_name: guardian_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "6465:80"
    networks:
      guardiannet:
        ipv4_address: 172.74.0.20
    environment:
      PMA_HOST: db
    restart: always
    container_name: guardian_phpmyadmin

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: guardian_rabbitmq
    ports:
      - "6440:15671"
      - "6441:5671"
    volumes:
      - ./config/rabbitmq/cert:/cert_rabbitmq/
      - guardian_rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "orangehrm"
      RABBITMQ_DEFAULT_PASS: "1234"
      RABBITMQ_SSL_CERTFILE: /cert_rabbitmq/orangehrm.crt
      RABBITMQ_SSL_KEYFILE: /cert_rabbitmq/orangehrm.key
      RABBITMQ_SSL_CACERTFILE: /cert_rabbitmq/orangehrm.crt
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: 'false'
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit ssl_listeners [{"::",5671}] -rabbit ssl_options [{certfile,"/cert_rabbitmq/orangehrm.crt"},{keyfile,"/cert_rabbitmq/orangehrm.key"},{cacertfile,"/cert_rabbitmq/orangehrm.crt"},{verify,verify_peer},{depth,3},{fail_if_no_peer_cert,false}] -rabbit tcp_listeners [{"::",5672}]'
    networks:
      guardiannet:
        ipv4_address: 172.74.0.5
    hostname: guardian-RabbitMQ
    restart: always

volumes:
  mariadb102:
  guardian_rabbitmq:

networks:
  guardiannet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.74.0.0/16
         gateway: 172.74.0.1
